services:
  employees-api:
    build:
      context: .
      dockerfile: dockerfiles/Employees.Api/Dockerfile
      target: dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=fortesdb;user=fortes;password=fortes_pass;TreatTinyAsBoolean=false
    volumes:
      - ./:/src
      - employees_api_bin:/src/Backends/Employees.Api/bin
      - employees_api_obj:/src/Backends/Employees.Api/obj
      - projects_api_bin:/src/Backends/Projects.Api/bin
      - projects_api_obj:/src/Backends/Projects.Api/obj
      - shared_bin:/src/Backends/Shared/bin
      - shared_obj:/src/Backends/Shared/obj

  projects-api:
    build:
      context: .
      dockerfile: dockerfiles/Projects.Api/Dockerfile
      target: dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=fortesdb;user=fortes;password=fortes_pass;TreatTinyAsBoolean=false
    volumes:
      - ./:/src
      - employees_api_bin:/src/Backends/Employees.Api/bin
      - employees_api_obj:/src/Backends/Employees.Api/obj
      - projects_api_bin:/src/Backends/Projects.Api/bin
      - projects_api_obj:/src/Backends/Projects.Api/obj
      - shared_bin:/src/Backends/Shared/bin
      - shared_obj:/src/Backends/Shared/obj

  projects-frontend:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    command: >
      sh -c "npm install &&
      npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"

  employees-frontend:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    command: >
      sh -c "npm install &&
      npm run dev -- --host 0.0.0.0 --port 5174 --strictPort"

volumes:
  employees_api_bin:
  employees_api_obj:
  projects_api_bin:
  projects_api_obj:
  shared_bin:
  shared_obj:

